@startuml
'https://plantuml.com/class-diagram
interface Prototype
{
   + {abstract} clone() : void
}

class Prototype1
{
    + clone() : void
}

class Prototype2
{
    + clone() : void
}

Prototype <|-- Prototype1
Prototype <|-- Prototype2

@enduml