@startuml

Class Client
Client : strategy : Strategy

Interface Strategy
Strategy : AbstractAlgorithm() : void

Class StrategyA
StrategyA : AbstractAlgorithm() : void

Class StrategyB
StrategyB : AbstractAlgorithm() : void

Class StrategyC
StrategyC : AbstractAlgorithm() : void



Client *-- Strategy
Strategy <|-- StrategyA
Strategy <|-- StrategyB
Strategy <|-- StrategyC

@endml
